### ISSUE TITLE
Please consider adjusting license to ISC/MIT

### ISSUE THREAD

**Issue by jhabdas** [johnpbloch/wordpress-core-installer#15]
Looks like you've produced nice tool many are finding value in, @johnpbloch.

I come from a JS development background and, as I work on my first WordPress plugin, have been noticing some licensing snafus I believe to be rooted in two things:

1. WordPress not making the switch to GitHub with the rest of the modern universe.
1. WordPress Foundation's intolerance for leaving license related questions open on the forums.

As a result of some of the licensing issues I've seen I've left some guidance on what I feel the proper structure should be for WP tools and the applications which used them to build themes and plugins here: https://github.com/xwp/wp-dev-lib/issues/240#issuecomment-303029913

And here's the most current, usable and authoritative reference I've found regarding licensing during my recent searches: https://choosealicense.com/licenses/

**Comment by johnpbloch** [comment]
Thanks for your interest in contributing. This project is already licensed under GPLv2+.

**Comment by jhabdas** [comment]
> This project is already licensed under GPLv2+.

Sigh. No one reads.

**Comment by johnpbloch** [comment]
No, I'm just uninterested in making the change you've suggested. Several of my open source packages are licensed under MIT. I know the license, I understand it. I specifically chose GPLv2+ for this project because I wanted it.
