### ISSUE TITLE
wp-config.php

### ISSUE THREAD

**Issue by aleclarson** [johnpbloch/wordpress-core-installer#21]
I'm using a custom `wp-config.php` that is added by a project generator.

How can I keep this installer from overwriting it, or is it safe?

**Comment by aleclarson** [comment]
I'll be keeping the real `wp-config.php` outside the wordpress root, but I still need a "dummy" `wp-config.php` where WordPress expects it to be which will require the real `wp-config.php`.

**Comment by johnpbloch** [comment]
WordPress core already handles having the config file one directory above `ABSPATH`. [Check out the logic in core](https://github.com/WordPress/WordPress/blob/master/wp-load.php#L26). So if you keep your wp-config.php file in the same directory that this installer puts WordPress core into it will automatically get picked up in the load sequence.

Let me know if that answered your question.

**Comment by aleclarson** [comment]
@johnpbloch Ah, very nice. Thanks John!
