### ISSUE TITLE
[question] when the execution of the script is indicated?

### ISSUE THREAD

**Issue by alber7rp** [johnpbloch/wordpress-core-installer#22]
Hello, first congratulations on the package, it works perfectly.
 I just had a question about the way it works, in the code, where do you indicate that the script should be executed to make the directory change ?, that is, do you use some type of script as "post-package-install"?
Thank you very much and apologize for this little doubt that I have.

**Comment by johnpbloch** [comment]
Thanks for stopping by! Composer itself has support for custom installers that can, among other things, change the installation location. You can read more on the subject in the Composer documentation: https://getcomposer.org/doc/articles/custom-installers.md

**Comment by alber7rp** [comment]
¡Muchas gracias!, le echaré un vistazo a la documentación que me has adjuntado, tengo que aprender más sobre Composer. De nuevo muchas gracias.
