### ISSUE TITLE
Deprecation Notices on php 8.2

### ISSUE THREAD

**Issue by jberculo** [johnpbloch/wordpress-core-installer#34]
Hi! First of all, thanks for your work! I am using this package now for a considerable time, but after a PHP upgrade (to 8.2) the following deprecation notices are logged. If you were able to find the time to fix this, it would be much appreciated!

Regards,
Joost.

`Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\DepthRangeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/finder/Iterator/DepthRangeFilterIterator.php:41
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/vendor/symfony/finder/Iterator/FilenameFilterIterator.php:28
Deprecation Notice: Return type of Composer\Repository\CompositeRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer/src/Composer/Repository/CompositeRepository.php:180`

**Comment by tomjn** [comment]
Do you have composer installers still set to v1 in your `composer.json`? I've several projects using this that don't encounter these deprecations on 8.2, what does your `composer.json` look like?

**Comment by jberculo** [comment]
Ah, thanks! I needed to update the composer version on my machine. I only thought it was related to this package b/c it was the first one.

**Comment by jberculo** [comment]
Closing...
