### ISSUE TITLE
wordpress-core-installer broken since last commit

### ISSUE THREAD

**Issue by actinism** [johnpbloch/wordpress-core-installer#6]
https://github.com/johnpbloch/wordpress-core-installer/commit/a04c2c383ef13aae077f36799ed2eafdebd618d2#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

"^1.0" breaks composer.phar install

*excerpt from vagrant composer.phar install*

Writing /home/vagrant/.composer/cache/repo/https---packagist.org/provider-johnpbloch$wordpress-core-installer.json into cache
  [RuntimeException]                                                                                                                                                                     
  Could not load package johnpbloch/wordpress-core-installer in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.0: Invalid version string "^1.0"

**Comment by Rarst** [comment]
Update your Composer?

**Comment by actinism** [comment]
That fixed the "^1.0", but now I have dependency errors for all wpackagist requirements... but it seems to work with a rollback and adding "composer-plugin-api": "1.0.0" to composer.json

**Comment by Rarst** [comment]
Which dependency errors?

**Comment by actinism** [comment]
to clarify, we're using an older wordpress-installation (3.9.x) in our backend production environment (not public available), and these are the wpackagist plugin versions:

    "wpackagist/co-authors-plus": "3.1.1",
    "wpackagist/duplicate-post": "2.6",
    "wpackagist/json-api": "1.1.1",
    "wpackagist/no-category-base-wpml": "1.1.0",
    "wpackagist/pods": "2.4.3",
    "wpackagist/polldaddy": "2.0.25",
    "wpackagist/wordpress-importer": "0.6.1",
    "wpackagist/bwp-minify": "1.3.3",
    "wpackagist-plugin/wp-embed-facebook": "1.8.3"

composer loads to ~/.composer/cache/repo/....json and stops with:
**Your requirements could not be resolved to an installable set of packages.**

In an other installation with slighty other versions it works. If I figure it out I'll will comment it here...

**Comment by Rarst** [comment]
Could you provide `composer.json` example exhibiting the issue? Not necessarily all of it, just the minimum it takes to run and see what happens there.

**Comment by actinism** [comment]
```
 "repositories": [
    {
      "type": "composer",
      "url": "http://wpackagist.org"
    }
  ],

  "require": {
    "alchemy/rabbitmq-management-client": "0.1.0",
    "jarednova/timber": "0.17.2",
    "composer-plugin-api": "1.0.0",
    "johnpbloch/wordpress": "3.9.1",
    "videlalvaro/php-amqplib": "v2.1.0",
    "wp-cli/wp-cli": "v0.15.0",
    "monolog/monolog": "1.9.1",

    "wpackagist/co-authors-plus": "3.1.1",
    "wpackagist/duplicate-post": "2.6",
    "wpackagist/json-api": "1.1.1",
    "wpackagist/no-category-base-wpml": "1.1.0",
    "wpackagist/pods": "2.4.3",
    "wpackagist/polldaddy": "2.0.25",
    "wpackagist/wordpress-importer": "0.6.1",
    "wpackagist/bwp-minify": "1.3.3",
    "wpackagist-plugin/wp-embed-facebook": "1.8.3"
  },

  "require-dev": {
    "squizlabs/php_codesniffer": "1.5.2",
    "phpunit/phpunit": "4.0.7"
  }
```

**Comment by Rarst** [comment]
`wpackagist/` namespace is deprecated, use `wpackagist-plugin/`. Also wrong Pods version. Otherwise this installs for me and has no issue with core installer.

**Comment by actinism** [comment]
Due to production environment we cannot upgrade any version now unless days of testing. ;-)

**Comment by Rarst** [comment]
There is no 2.4.3 version of Pods available from official repo at the moment https://wordpress.org/plugins/pods/developers/

**Comment by actinism** [comment]
I see... In an other environment we used wp 4.2.2 and pods 2.5.1.2 ... that's also not available. :-( Well this seems to be an overall issue due to different components and not really related to the core-installer.

May I should close this issue for now
