### ISSUE TITLE
Installer removes all contents with update

### ISSUE THREAD

**Issue by kamilszewczyk** [johnpbloch/wordpress-core-installer#7]
Hi,
I'm investigating possibilities of using composer to install wordpress core as a dependency. I looks really nice, however I did notice that the installer always purge the directory when installing/updating core. This proves the whole update process unusable, as all custom plugins or themes are removed as well. No to mention that even custom directories (one with Magento installed) are also removed.
Would it be possible to change that behaviour?

**Comment by Rarst** [comment]
Configure your content directory to reside outside the core, that's the normal practice.

**Comment by kamilszewczyk** [comment]
@Rarst - that doesn't really sound like a solution for me. I got Magento that resides in subfolder along with Wordpress files, so I would need to move it outside of the core as well? However, Magento composer installer is intelligent enough to update only it's own files and doesn't remove everything else in the process...

**Comment by Rarst** [comment]
It will grow on you. :) Separating content from application files is normal practice, that well predates Composer, even for WP.

I am not sure why would you possibly want Magento inside WP core. If you have core at site root I recommend to move away from that as well, in favor of dedicated directory for it.

**Comment by kamilszewczyk** [comment]
@Rarst - it does exists in separate directory ;).
We did find an example how we could move wordpress core into separate directory that can be update without overriding contents of root directory, so that question is no longer valid :). 

Thanks for the help
